# Generated by Django 4.2.2 on 2023-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('confused', 'Confused'), ('fearful', 'Fearful'), ('disgusted', 'Disgusted'), ('low_self_esteem', 'Low Self Esteem'), ('inspired', 'Inspired'), ('joyful', 'Joyful'), ('enthusiastic', 'Enthusiastic'), ('high_self_esteem', 'High Self Esteem'), ('grateful', 'Gratified'), ('amazingly good', 'Amazingly Good'), ('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad'), ('relationships', 'Relationships'), ('lifelessness', 'Lifelessness'), ('depression', 'Depression'), ('pain', 'Pain'), ('shame', 'Shame'), ('guilt', 'Guilt'), ('frustration', 'Frustration'), ('tense', 'Tense'), ('irritated', 'Irritated'), ('boredom', 'Boredom'), ('worried', 'Worried'), ('insecurity', 'Insecurity'), ('ADHD', 'ADHD'), ('anxiety', 'Anxiety')], default='neutral', max_length=100)),
                ('role', models.CharField(choices=[('client', 'Client'), ('therapist', 'Therapist')], default='client', max_length=25)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profile_avatars')),
            ],
        ),
    ]
